version: '3.7'
services:
  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres2:/var/lib/postgresql/data

volumes:
  postgres2:
  postgres:
    name: nest-db
